swiftmailer:
    transport: gmail
    host: smtp.gmail.com
    username: '%env(MAILER_USERNAME)%'
    password: '%env(MAILER_PASSWORD)%'
    encryption: ssl
    auth_mode: login
    port: 465
    logging: true
    spool: { type: 'memory' }
    stream_options:
        ssl:
            allow_self_signed: true
            verify_peer: false
            verify_peer_name: false
