version: '3.2'

services:
  postgres:
    image: postgres:latest
    hostname: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
      - /data/postgres:/data/postgres
    restart: always
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:latest
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@mail.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin
    volumes:
      - /data/pgadmin:/root/.pgadmin
    ports:
      - "5050:80"
    restart: always