version: '3'

services:
  php:
    build:
      context: ./
      dockerfile: .docker/Dockerfile
    container_name: php
    depends_on:
      - postgres
    env_file:
      - ./.env
    volumes:
      - ./:/srv/symfony:rw,cached
    environment:
      XDEBUG_CONFIG: "remote_host=docker.for.mac.localhost idekey=IDE_XDEBUG"

  symfony:
    build:
      context: ./
      dockerfile: .docker/nginx/Dockerfile
    container_name: symfony
    depends_on:
      - php
    ports:
      - "8080:80"
    volumes:
      - ./public:/srv/symfony/public:ro

  postgres:
    image: postgres:9.6-alpine
    container_name: postgres
    environment:
      - POSTGRES_DB=symfony
      - POSTGRES_USER=symfony
      - POSTGRES_PASSWORD=symfony
      - PGDATA=/var/lib/postgresql/data/db-files/
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    container_name: adminer
    depends_on:
      - postgres
    restart: always
    ports:
      - 2000:8080

volumes:
  db-data: {}
